# Generated by Django 3.0.7 on 2021-01-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppId', models.CharField(max_length=100)),
                ('Token', models.CharField(max_length=100)),
                ('Channel', models.CharField(max_length=100)),
            ],
        ),
    ]
