# Generated by Django 3.0.7 on 2021-01-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keys',
            options={'verbose_name_plural': 'Keys'},
        ),
        migrations.AlterField(
            model_name='keys',
            name='AppId',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='keys',
            name='Channel',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='keys',
            name='Token',
            field=models.CharField(max_length=300),
        ),
    ]
