# Generated by Django 3.0.7 on 2021-01-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20210121_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keys',
            name='Token',
        ),
        migrations.AddField(
            model_name='keys',
            name='appCertificate',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
